name: Publish Package on Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name
        id: get_tag
        run: |
          env
          echo " env vars are $*"
          cat $GITHUB_EVENT_PATH
          echo "TAG_NAME=$(echo ${{ github.ref }} | sed 's#refs/tags/##')" >> $GITHUB_ENV
          echo "tag name is ${{ steps.get_tag.outputs.TAG_NAME }}"
          echo "GITHUB_REF is ${{ github.ref }}"
          echo "GITHUB_SHA is ${{ github.sha }}"
          echo "GITHUB_ACTOR is ${{ github.actor }}"
          echo "GITHUB_REF_NAME is ${{ github.ref_slug }}"
          echo "GITHUB_REF_SLUG is ${{ github.ref_slug }}"


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.8.3'

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts-${{ steps.get_tag.outputs.TAG_NAME }}

      - name: Publish package
        run: poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
